#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "$(tput setaf 2)Running pre-push checks...$(tput sgr0)"

# Run linting
echo "$(tput setaf 2)Running lint checks...$(tput sgr0)"
npm run lint
lint_status=$?

# Run build
echo "$(tput setaf 2)Running build...$(tput sgr0)"
npm run build
build_status=$?

# Check if any of the checks failed
if [ "$lint_status" != 0 ] || [ "$build_status" != 0 ]; then
  echo "$(tput setaf 1)Pre-push checks failed. Push aborted.$(tput sgr0)"
  exit 1
fi

# Temporarily commenting out webhook notification due to curl issues
# echo "$(tput setaf 2)Sending pre-push notification...$(tput sgr0)"
# curl -X POST -H 'Content-type: application/json' \
# --data "{\"text\":\"Push completed by $(logname) on branch $(git rev-parse --abbrev-ref HEAD) with commit: $(git log -1 --pretty=%B)\"}" \
# "$WEBHOOK_URL"

echo "$(tput setaf 2)Pre-push checks passed. Proceeding with push.$(tput sgr0)"
